version: '3.0'

services:

  client:
    container_name: react-client
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    container_name: node-server
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"
      - "3001:3001"
    depends_on:
      - redis
    links:
      - "redis:redis.internal"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - .cache:/data